copy 196.Swap_Numbers\bin\Debug\test.txt 196.Swap_Numbers
copy 199.String_mask\bin\Debug\test.txt 199.String_mask
copy 202.Stepwise_word\bin\Debug\test.txt 202.Stepwise_word
copy 203.Strings_and_arrows\bin\Debug\test.txt 203.Strings_and_arrows
copy 205.Clean_up_the_words\bin\Debug\test.txt 205.Clean_up_the_words
copy 208.Find_the_highest_score\bin\Debug\test.txt 208.Find_the_highest_score
copy 211.Chardonnay_or_Cabernet\bin\Debug\test.txt 211.Chardonnay_or_Cabernet
copy 214.Time_to_eat\bin\Debug\test.txt 214.Time_to_eat
copy 217.One_zero_two_zeros\bin\Debug\test.txt 217.One_zero_two_zeros
copy 220.Trick_or_Treat\bin\Debug\test.txt 220.Trick_or_Treat
copy 222.Black_card\bin\Debug\test.txt 222.Black_card
copy 225.Testing\bin\Debug\test.txt 225.Testing
copy 227.Real_fake\bin\Debug\test.txt 227.Real_fake
copy 230.Football\bin\Debug\test.txt 230.Football
copy 232.Not_so_clever\bin\Debug\test.txt 232.Not_so_clever
copy 235.Simple_or_Trump\bin\Debug\test.txt 235.Simple_or_Trump
copy 237.Panacea_-_truth_or_lie\bin\Debug\test.txt 237.Panacea_-_truth_or_lie
copy 240.Mersenne_prime\bin\Debug\test.txt 240.Mersenne_prime
